application:
  base_url: "http://0.0.0.0:8000"
  host: 0.0.0.0
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "something@gmail.com"
database:
  host: "postgres.chsquq2sgymf.us-east-2.rds.amazonaws.com"
  port: 5432
  username: "postgres"
  password: "postgres"
  database_name: "postgres"
  require_ssl: false
redis_url: "redis://rediszero2prod-r4jcne.serverless.use2.cache.amazonaws.com:6379"
