application:
  base_url: "http://0.0.0.0:8000"
  host: 0.0.0.0
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "something@gmail.com"
database:
  host: "db"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "postgres"
  require_ssl: false
redis_url: "redis://redis:6379"
