version: '3'

networks:
  application:

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - application
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - application
  app:
    container_name: zero2prod
    image: 996899389712.dkr.ecr.us-east-1.amazonaws.com/zero2:latest
    ports:
      - "8080:8080"
   # build:
   #   context: .
   #   dockerfile: Dockerfile
   # healthcheck:
   #   start_period: 20s
    # environment:
    #   - APP_DATABASE_HOST=127.0.0.1
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    networks:
      - application

volumes:
  dbdata:
    driver: local
