version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgre-t
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    image: my_app
    environment:
      - APP_DATABASE_HOST=127.0.0.1
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  dbdata:
    driver: local
