version: '3'

networks:
  application:

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - application
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - application
  app:
    container_name: zero2prod
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      start_period: 20s
    # environment:
    #   - APP_DATABASE_HOST=127.0.0.1
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    networks:
      - application
    ports:
      - "8000:8000"

volumes:
  dbdata:
    driver: local
