name: zero2 cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
     
    # - name: Rust setupp
    #   uses: actions/setup-rust@v1
    #   with:
    #     rust-version: stable

    # - name: Build and tests
    #   run: cargo build --release

    - name: AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 851725641243.dkr.ecr.us-east-2.amazonaws.com

    - name: Docker build for AWS
      run: docker build -t zero2prod --platform=linux/arm/v6 .

    - name: Tag created image
      run: docker tag zero2prod:latest 851725641243.dkr.ecr.us-east-2.amazonaws.com/zero2prod:latest

    - name: Push image to AWS
      run: docker push 851725641243.dkr.ecr.us-east-2.amazonaws.com/zero2prod:latest

    - name: Rerun task in AWS with a new image
      run: aws ecs update-service --cluster zero2prod-arm-cluster --service zero2prod-service --force-new-deployment

    # - name: Restart Rust App
    #   run: ssh -i /home/ubuntu/zero2.pem ubuntu@ec2-54-163-199-15.compute-1.amazonaws.com 'sudo docker-compose -f /home/ubuntu/docker-compose2.yml up -d'